// Converts the docs CSVs into typed TS data modules under data/reference/.
// Run with: node scripts/convert-csv.mjs
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');
const docs = join(root, 'docs');
const outDir = join(root, 'data', 'reference');
mkdirSync(outDir, { recursive: true });

// Minimal RFC-4180-ish CSV parser (handles quotes, escaped quotes, commas, newlines).
function parseCsv(text) {
  text = text.replace(/^\uFEFF/, ''); // strip BOM
  const rows = [];
  let row = [];
  let field = '';
  let inQuotes = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (inQuotes) {
      if (c === '"') {
        if (text[i + 1] === '"') { field += '"'; i++; }
        else inQuotes = false;
      } else field += c;
    } else {
      if (c === '"') inQuotes = true;
      else if (c === ',') { row.push(field); field = ''; }
      else if (c === '\r') { /* ignore */ }
      else if (c === '\n') { row.push(field); rows.push(row); row = []; field = ''; }
      else field += c;
    }
  }
  if (field.length > 0 || row.length > 0) { row.push(field); rows.push(row); }
  return rows.filter(r => r.some(v => v.trim() !== ''));
}

function toRecords(csvText) {
  const rows = parseCsv(csvText);
  const header = rows[0].map(h => h.trim());
  return rows.slice(1).map(r => {
    const obj = {};
    header.forEach((h, i) => { obj[h] = (r[i] ?? '').trim(); });
    return obj;
  });
}

const banner = '// AUTO-GENERATED by scripts/convert-csv.mjs from docs/*.csv. Do not edit by hand.\n';

// users.csv -> data/reference/users.ts
const userRecords = toRecords(readFileSync(join(docs, 'users.csv'), 'utf8'));
const users = userRecords.map(r => ({
  name: r['Name'],
  grade: r['Grade'],
  title: r['Title'],
  reportsTo: r['Reports To'],
  level: Number(r['Level']) || 0,
  entity: r['Entity'],
  market: r['Market'],
  lineOfBusiness: r['Line Of Business'],
  serviceLine: r['Service Line'],
  departHead: r['Depart. Head'],
  teamHead: r['Team Head'],
  messageOwner: r['Message Owner'],
  businessLine1stLevel: r['Business Line 1st Level'],
  businessLine2ndLevel: r['Business Line 2nd Level'],
  businessTeam: r['Business Team'],
  businessContact: r['Business Contact'],
}));
writeFileSync(
  join(outDir, 'users.ts'),
  banner +
  "import { OrgUser } from '@/types';\n\n" +
  'export const orgUsers: OrgUser[] = ' + JSON.stringify(users, null, 2) + ';\n'
);

// use-case-channel-rules.csv -> data/reference/channel-rules.ts
const ruleRecords = toRecords(readFileSync(join(docs, 'use-case-channel-rules.csv'), 'utf8'));
const rules = ruleRecords.map(r => ({
  use_case_id: r['use_case_id'],
  channel: r['channel'],
  priority: r['priority'],
  app_name: r['app_name'],
  send_to_china_flag: r['send_to_china_flag'],
  traffic_percentage: r['traffic_percentage'],
  sender: r['sender'],
  sender_name: r['sender_name'],
  cost_center_id: r['cost_center_id'],
  encrypt_type: r['encrypt_type'],
}));
writeFileSync(
  join(outDir, 'channel-rules.ts'),
  banner +
  "import { ChannelRule } from '@/types';\n\n" +
  'export const channelRules: ChannelRule[] = ' + JSON.stringify(rules, null, 2) + ';\n'
);

// use-cases.csv -> data/reference/use-cases.ts
const ucRecords = toRecords(readFileSync(join(docs, 'use-cases.csv'), 'utf8'));
const numericFields = new Set([
  'push_bounce_back_period', 'sms_bounce_back_period',
  'email_bounce_back_period', 'letter_bounce_back_period',
]);

const useCases = ucRecords.map(r => {
  const values = {};
  for (const [k, v] of Object.entries(r)) {
    if (k === 'use_case_id' || k === 'auto_populated') continue;
    if (v === '' || v == null) continue;
    values[k] = numericFields.has(k) ? Number(v) : v;
  }
  const autoPopulated = (r['auto_populated'] || '')
    .split(',').map(s => s.trim()).filter(Boolean);
  return {
    use_case_id: r['use_case_id'],
    values,
    autoPopulated,
    channelRules: rules.filter(rule => rule.use_case_id === r['use_case_id']),
  };
});
writeFileSync(
  join(outDir, 'use-cases.ts'),
  banner +
  "import { ReferenceUseCaseFull } from '@/types';\n\n" +
  'export const referenceUseCases: ReferenceUseCaseFull[] = ' + JSON.stringify(useCases, null, 2) + ';\n'
);

console.log(`Generated: ${users.length} users, ${rules.length} channel rules, ${useCases.length} use cases.`);
