// AUTO-GENERATED by scripts/convert-csv.mjs from docs/*.csv. Do not edit by hand.
import { ChannelRule } from '@/types';

export const channelRules: ChannelRule[] = [
  {
    "use_case_id": "UC-001",
    "channel": "SMS",
    "priority": "High",
    "app_name": "",
    "send_to_china_flag": "No",
    "traffic_percentage": "HTCL-100%, CSL-0%",
    "sender": "HASE",
    "sender_name": "",
    "cost_center_id": "25267613",
    "encrypt_type": ""
  },
  {
    "use_case_id": "UC-001",
    "channel": "PUSH",
    "priority": "Medium",
    "app_name": "HASE_Mobile",
    "send_to_china_flag": "",
    "traffic_percentage": "DAASC-100%",
    "sender": "",
    "sender_name": "",
    "cost_center_id": "",
    "encrypt_type": ""
  },
  {
    "use_case_id": "UC-002",
    "channel": "EMAIL",
    "priority": "High",
    "app_name": "",
    "send_to_china_flag": "",
    "traffic_percentage": "HTCL-100%",
    "sender": "hangseng@mail.test.hangseng.com",
    "sender_name": "恒生銀行 Hang Seng Bank",
    "cost_center_id": "",
    "encrypt_type": "TLS"
  },
  {
    "use_case_id": "UC-002",
    "channel": "LETTER",
    "priority": "Low",
    "app_name": "",
    "send_to_china_flag": "",
    "traffic_percentage": "",
    "sender": "",
    "sender_name": "",
    "cost_center_id": "",
    "encrypt_type": ""
  },
  {
    "use_case_id": "UC-003",
    "channel": "PUSH",
    "priority": "High",
    "app_name": "HASE_Mobile",
    "send_to_china_flag": "",
    "traffic_percentage": "DAASC-100%",
    "sender": "",
    "sender_name": "",
    "cost_center_id": "",
    "encrypt_type": ""
  },
  {
    "use_case_id": "UC-003",
    "channel": "EMAIL",
    "priority": "Medium",
    "app_name": "",
    "send_to_china_flag": "",
    "traffic_percentage": "HTCL-100%",
    "sender": "hangseng@mail.info.hangseng.com",
    "sender_name": "恒生銀行信用卡 Hang Seng Bank Credit Card",
    "cost_center_id": "",
    "encrypt_type": "TLS"
  },
  {
    "use_case_id": "UC-004",
    "channel": "SMS",
    "priority": "High",
    "app_name": "",
    "send_to_china_flag": "No",
    "traffic_percentage": "HTCL-70%, CSL-30%",
    "sender": "HASE",
    "sender_name": "",
    "cost_center_id": "25267614",
    "encrypt_type": ""
  },
  {
    "use_case_id": "UC-004",
    "channel": "PUSH",
    "priority": "Medium",
    "app_name": "HASE_Mobile_DAASC",
    "send_to_china_flag": "",
    "traffic_percentage": "DAASC-100%",
    "sender": "",
    "sender_name": "",
    "cost_center_id": "",
    "encrypt_type": ""
  },
  {
    "use_case_id": "UC-005",
    "channel": "SMS",
    "priority": "High",
    "app_name": "",
    "send_to_china_flag": "No",
    "traffic_percentage": "HTCL-100%, CSL-0%",
    "sender": "HASE",
    "sender_name": "",
    "cost_center_id": "25267615",
    "encrypt_type": ""
  },
  {
    "use_case_id": "UC-005",
    "channel": "EMAIL",
    "priority": "Medium",
    "app_name": "",
    "send_to_china_flag": "",
    "traffic_percentage": "HTCL-100%",
    "sender": "commercial@mail.info.hangseng.com",
    "sender_name": "恒生商業銀行 Hang Seng Commercial Banking",
    "cost_center_id": "",
    "encrypt_type": "TLS"
  }
];
